[project]
name = "laksiri-en-si-translation-gradio-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.41.1",
    "requests>=2.32.4",
    "setuptools>=80.9.0",
]
